#!/bin/bash
echo ''
echo ''
echo '============ Set up as determined by /dba/bin/updSchema ================='
echo 'Instance        = xxxxxdvl'
echo 'Group           = xxxxx'
echo 'Install Scripts = xxxxx.vw.cr.sql'
echo 'Install file    = /dba/temp/xxxxx.214686.install.xxxxxdvl.xxxxx.list'
echo 'Use Wrapper     = Y'
echo 'Batch           = Y'
echo 'DB Env          = N'
echo '============================================================'
echo ''
echo 'Start of get_parameters'
echo '=========================================='
echo 'install_sid   = xxxxxdvl'
echo 'install_group = xxxxx'
echo 'install_file  = /dba/temp/xxxxx.214686.install.xxxxxdvl.xxxxx.list'
echo 'wrap          = Y'
echo 'batch         = Y'
echo 'db_env        = N'
echo '=========================================='
echo 'End of get_parameters'
echo ''
echo 'Start of set_globals'
echo 'No Storage File specific to xxxxxdvl/install_group found.  Using default.'
echo 'No Action File specific to xxxxx found.  Using default.'
echo 'migration_dir      = /dba/etc/migration.d'
echo 'temp_dir           = /dba/temp'
echo 'password_file      = /dba/etc/prodctl_xxxxxdvl.pwd'
echo 'schema_tokens_file = /dba/etc/migration.d/schema_tokens.xxxxx.dat'
echo 'grant_file         = /dba/etc/migration.d/grants.xxxxx.dat'
echo 'owner_file         = /dba/etc/migration.d/object_owner.xxxxx.dat'
echo 'storage_file       = /dba/etc/migration.d/storage.dat'
echo 'sql_load_file      = /home/xxxxx/updSchema/xxxxx.250505.214686.sql'
echo 'sql_temp_file      = /dba/temp/temp.214686.load.iadmfgappdev01.xxxxxdvl.xxxxx.sql'
echo 'sed_temp_file      = /dba/temp/temp.214686.sed.iadmfgappdev01.xxxxxdvl.xxxxx.sed'
echo 'grant_temp_file    = /dba/temp/temp.214686.grants.iadmfgappdev01.xxxxxdvl.xxxxx.sql'
echo 'grant_runner       = /dba/etc/migration.d/create_grants.sh'
echo 'End of set_globals'
echo ''
echo 'Start of create_sed_temp_file'
echo 'User token SYS not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token SYSTEM not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token ORDSYS not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token ORDPLUGINS not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token APPLSYS not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token APPLSYSPUB not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token ALR not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token AX not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token AK not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token XLA not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token GL not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token RG not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token FA not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token FEM not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token CS not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token AP not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token AR not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token OE not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token WIP not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IBP not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IBA not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IBY not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IBE not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IBU not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token FII not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token HRI not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token POA not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token ONT not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IEU not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IEM not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token OKE not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token ECX not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token WSM not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token MWA not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'User token IGC not in file /dba/etc/prodctl_xxxxxdvl.pwd.'
echo 'End of create_sed_temp_file'
echo ''
echo '============= Sourcing File:  xxxxx.vw.cr.sql =============================='
echo ' '
echo '**R122: Special grants check.**'
echo '**R122: GRANT_ALLOWED not set.   Now looking for special grants in sql code now **'
echo '**R122: Special grant check.  No special grant code found. Continuing with migration.**'
echo ' '
echo 'Start of wrap_prep for xxxxx.vw.cr.sql'
echo 'nawk: warning: escape sequence `.'\'' treated as plain `.'\''' >&2
echo 'object_name       = xxxxx'
echo 'object_type_abr   = VW'
echo 'object_action_abr = CR'
echo 'owner_token       = APPS'
echo 'object_type       = VIEW'
echo 'grant_action      = YES'
echo 'sysnonym_action   = '
echo 'object_action     = CREATE'
echo 'End of wrap_prep'
echo ''
echo 'Start of append_to_sql_load_file'
echo 'End of append_to_sql_load_file'
echo ''
echo 'Start of wrap_grants'
echo 'Starting create_grants for... 1: APPS VIEW xxxxx APPS' >&2
echo 'OK:  Create grant to TKF' >&2
echo 'OK:  Create grant to TKO' >&2
echo 'OK:  Create grant to TKR' >&2
echo 'Current value of pSkipTokenList=<APPS:TKF:TKO:TKR>' >&2
echo 'Returning with value=<TKF:TKO:TKR>' >&2
echo 'Ending create_grants for...1: APPS VIEW xxxxx APPS:TKF:TKO:TKR' >&2
echo 'End of wrap_grants'
echo ''
echo '============= End File:  xxxxx.vw.cr.sql ==================================='
echo ''
echo 'Start of substitute_variables'
echo 'End of substitute_variables'
echo ''
echo 'Starting check edition type'
echo ' '
echo 'Check edition status. Cleared to proceed with migration'
echo ' '
echo ''
echo 'SQL*Plus: Release 10.1.0.5.0 - Production on Mon May 5 11:07:55 2025'
echo ''
echo 'Copyright (c) 1982, 2005, Oracle.  All rights reserved.'
echo ''
echo 'Enter user-name: '
echo 'Connected to:'
echo 'Oracle Database 19c EE High Perf Release 19.0.0.0.0 - Production'
echo ''
echo 'SQL> SQL> xxxxxdvl:xxxxx>'
echo '============= Sourcing File:  xxxxx.vw.cr.sql =============================='
echo 'File:  xxxxx.vw.cr.sql Mon May  5 11:07:55 PDT 2025'
echo 'Connected.'
echo 'xxxxxdvl:xxxxx>/******************************************************************************'
echo 'xxxxxdvl:xxxxx>** Filename:	     $Workfile:   xxxxx.vw.cr.sql  $'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>** Revision:	     $Revision: 1.3 $'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>** Date Last'
echo 'xxxxxdvl:xxxxx>** Modified:	     $Date: 2025/03/26 09:10:45 $'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>** Last'
echo 'xxxxxdvl:xxxxx>** Modified By:	     $Author: xxxxx $'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>** Description:'
echo 'xxxxxdvl:xxxxx>	       Create a view for item descriptions'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>** $Log: xxxxx.vw.cr.sql,v $'
echo 'xxxxxdvl:xxxxx>** Revision 1.3	2025/03/26 09:10:45  xxxxx'
echo 'xxxxxdvl:xxxxx>** xxxxx - Enabling German Language-modified'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>** Revision 1.2	2025/03/09 11:54:35  xxxxx'
echo 'xxxxxdvl:xxxxx>** xxxxx - Enabling German Language'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>** Revision 1.1	2015/06/18 13:54:56  xxxxx'
echo 'xxxxxdvl:xxxxx>** Initial revision'
echo 'xxxxxdvl:xxxxx>**'
echo 'xxxxxdvl:xxxxx>--'
echo 'xxxxxdvl:xxxxx>--   Rev 1.0   18 Jun 2015 13:54:56   xxxxx'
echo 'xxxxxdvl:xxxxx>--M 108145 - new view'
echo 'xxxxxdvl:xxxxx>--'
echo 'xxxxxdvl:xxxxx>--'
echo 'xxxxxdvl:xxxxx>******************************************************************************/'
echo 'xxxxxdvl:xxxxx>set verify on;'
echo 'xxxxxdvl:xxxxx>set echo on;'
echo 'xxxxxdvl:xxxxx>'
echo 'xxxxxdvl:xxxxx>create or replace view xxxxx as'
echo '  2    select'
echo '  3  	 msi.segment1 item,'
echo '  4  '
echo 'xxxxxdvl:xxxxx>	 /* Start: Enabling German Language in Oracle EBS*/'
echo 'xxxxxdvl:xxxxx>	 --, msi.description'
echo 'xxxxxdvl:xxxxx>tk_inv_utl.tk_translated_itemdesc(msi.inventory_item_id) description'
echo 'SP2-0734: unknown command beginning "tk_inv_utl..." - rest of line ignored.'
echo 'xxxxxdvl:xxxxx>/* End: Enabling German Language in Oracle EBS*/'
echo 'xxxxxdvl:xxxxx>	 from'
echo 'SP2-0042: unknown command "from" - rest of line ignored.'
echo 'xxxxxdvl:xxxxx>	   apps.mtl_system_items_b msi'
echo 'SP2-0734: unknown command beginning "apps.mtl_s..." - rest of line ignored.'
echo 'xxxxxdvl:xxxxx>	 where '\''$Revision: 1.3 $'\'' is not null	/* This clause must be present! */'
echo 'SP2-0734: unknown command beginning "where '\''$Re..." - rest of line ignored.'
echo 'xxxxxdvl:xxxxx>	   and msi.segment2 is null'
echo 'SP2-0734: unknown command beginning "and msi.se..." - rest of line ignored.'
echo 'SP2-0044: For a list of known commands enter HELP'
echo 'and to leave enter EXIT.'
echo 'xxxxxdvl:xxxxx>	   and msi.organization_id = 82'
echo 'SP2-0734: unknown command beginning "and msi.or..." - rest of line ignored.'
echo 'xxxxxdvl:xxxxx>/'
echo '    msi.segment1 item,'
echo '                     *'
echo 'ERROR at line 3:'
echo 'ORA-00936: missing expression'
echo ''
echo ''
echo 'Disconnected from Oracle Database 19c EE High Perf Release 19.0.0.0.0 - Production'
echo ''
echo 'Schema Update Script: /home/xxxxx/updSchema/xxxxx.250505.214686.sql'
echo 'Schema Update Log:    /home/xxxxx/updSchema/xxxxx.250505.214686.log'
echo ''
echo ''

exit 2